# 5.16 List Dua Dimensi

In [1]:
#Berikut merupakan contoh variabel yang memuat list dua dimensi.
matrik_01 = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
]
#List dua dimensi disini akan membentuk sebuah matriks.
#Walaupun terlihat seperti sebuah list, namun ini dianggap sistem sebagai sebuah matriks.
#Dibawah ini adalah perintah untuk mencetak list dua dimensi tersebut:
print(matrik_01)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]


In [2]:
#Untuk menampilkan baris yang kita inginkan, kita harus tau bahwa 
#di dalam python urutan angka dimulai dari 0,1,2 dan seterusnya.
#Jadi jika ingin memanggil baris kedua maka inputannya 1.
#Dibawah ini adalah perintah untuk memanggil baris kedua
matrik_01[1]

[5, 6, 7, 8]

In [3]:
#Begitu pula untuk memanggil suatu elemen dalam matriks.
#Perintahnya dimulai dari baris terlebih dahulu kemudian dilanjutkan dengan kolomnya.
#Misal kita ingin mengambil elemen dari baris ke 2 dan kolom ke 3,
#maka hal yang kita input adalah baris ke 1 dan kolom ke 2.
#Intinya urutan bilangan dalam python dimulai dari 0,1,2 dan seterusnya.
#Berikut adalah contoh perintahnya
matrik_01[1][2]

7

In [4]:
#Berikut adalah perintah untuk memanggil anggota dari list dua dimensi tersebut
for baris in matrik_01 :
    print(baris)
#Diatas ini adalah cara untuk mencetak baris didalam matriks
    for kolom in baris:
        print(kolom)
#Setelah baris tersebut dicetak, akan masuk ke dalam perintah ini dan akan mencetak
#list di dalam baris pertama yang dipanggil.
#Perintah ini akan terus berulang sampai tidak ada lagi elemen di dalam variabel list 
#dua dimensi tersebut.

#**************************
#Berikut adalah keluarannya
#**************************

[1, 2, 3, 4]
1
2
3
4
[5, 6, 7, 8]
5
6
7
8
[9, 10, 11, 12]
9
10
11
12
[13, 14, 15, 16]
13
14
15
16


In [5]:
#untuk memanggil list dua dimensi tersebut kembali, tinggal mengetik nama variabelnya saja
matrik_01

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]

# 5.17 Tuples

In [6]:
#Tuples merupakan inisiasi variabel yang mirip dengan list.
#Namun bedanya tuples ini tidak dapat diganti atau dirubah isinya.
#Jika didalam suatu kesempatan kita ingin membuat data yang pakem,
#maka tuples inilah jawabannya.
#Contoh Tuples :
Angka_01 = (0,1,2,3,4,5)
#Jadi dalam tuples ini menggunakan kurung biasa "()" dalam penggunaannya.

In [7]:
#untuk mencetak suatu elemen didalam tuples tersebut kita bisa menggunakan perintah seperti biasanya.
#Berikut perintah untuk mencetak elemen di dalam tuples tersebut :
print(Angka_01[0])

0


In [8]:
#Untuk mencetak urutan elemen didalam tuples, kita dapat menggunakan perintah seperti biasanya juga,
#dengan urutan pertama yang kita ingin sampai urutan terakhir yang kita inginkan juga
#REMINDER : urutan bilangan dalam python dimulai dari 0.
#Berikut contoh perintahnya :
print(Angka_01[0:4])

(0, 1, 2, 3)


In [9]:
#Untuk mencetak list dari urutan yang kita piih dalam tuples dapat menggunakan
#perintah for .... in variabel [urutan pertama]:[urutan terakhir]:
#Berikut contohnya :
for blabla in Angka_01[0:4]:
    print(blabla)

0
1
2
3


In [10]:
#Berikut adalah beberapa perintah yang tidak dapat digunakan dalam Tuples.
#yang pertama :
Angka_01[0] = 7
#Perintah ini bertujuan untuk mengubah elemen pertama dari Tuples tersebut menjadi 7
#Namun sesuai definisi tuples, perintah ini tidak dapat dijalankan

#yang kedua :
Angka_01.append(7)
#Perintah ini bertujuan untuk menambahkan 7 didalam Tuples.
#Sesuai definisi tuples, perintah ini tidak dapat dijalankan.

#yang ketiga :
Angka_01.remove(4)
#Perintah ini bertujuan untuk menghilangkan 4 didalam Tuples tersebut.
#Tidak dapat dijalankan sesuai definisi tuples yang tidak bisa menambahkan dan menghapus data dalam tuples.

#Berikut adalah keluaran yang akan keluar jika kita menggunakan ketiga contoh tersebut
#ERROR

TypeError: 'tuple' object does not support item assignment

In [11]:
#Berikut adalah cara untuk mengetahui berapa banyak 'data' yang terdapat di dalam tuples
Angka_01.count(3)
#disini 3 hanya terdapat 1 buah di dalam tuples,
#maka keluaran yang dicetak adalah 1

1

In [12]:
#Untuk mencari urutan keberapa sebuah 'data' yang ingin kita cari,
#kita dapat menggunakan fungsi variabel.index(data yang ingin dicari)
#Berikut contohnya :
Angka_01.index(3)
#Disini akan dicetak 3, sesuai urutan python yang dimulai dari 0
#maka urutan angka 3 ini berada di urutan keempat.

3

# 5.18 Dictionaries

In [13]:
#Berikut adalah contoh data dictionaries dengan tipe data string :
data_negara_01 = {
    "nama" : "Indonesia",
    "kepala_pemerintahan" : "Persiden",
    "apakah_merdeka" : True,
    "tanggalmerdeka" : '17-8-1945',
    "umur" : 78
}
#untuk memanggil suatu data didalam dictionaries perlu menggunakan tanda '[]'
print("Nama Negara : ",data_negara_01['nama'])
print("Kepala Pemerintahan : ",data_negara_01['kepala_pemerintahan'])
print("Apakah Sudah Merdeka : " , data_negara_01['apakah_merdeka'], '\n') 

#dapat menambahkan .get setelah variabel untuk memperjelas pemanggilannya.
#Namun didalam .get ini menggunakan tanda kurung biasa'()
print("Jika Sudah Merdeka, Kapan Tanggal Kemerdekaannya : ", data_negara_01.get('tanggalmerdeka'))
print("Maka Sekarang Umur Negara Tersebut Adalah : ", data_negara_01.get('umur'))

#AKAN DICETAK SEBAGAI BERIKUT

Nama Negara :  Indonesia
Kepala Pemerintahan :  Persiden
Apakah Sudah Merdeka :  True 

Jika Sudah Merdeka, Kapan Tanggal Kemerdekaannya :  17-8-1945
Maka Sekarang Umur Negara Tersebut Adalah :  78


# 5.19 Fungsi dalam Python

In [14]:
#berikut adalah contoh fungsi di dalam Python
#disini kita ingin memnbuat sebuah fungsi tentang nama lengkap dari seseorang.

#Sebagai gambaran umum, disini kita masukkan nama orang yang memiliki dua kata.
#karena dua kata, kita memerlukan dua variabel di dalam fungsi ini.
#variabel pertama saya beri nama first_name
#variabel kedua diberi nama last_name
#disini fungsinya adalah variabel first_name 'spasi' last_name
def full_nama(first_name, last_name):
    print(f"Nama lengkapnya adalah {first_name} {last_name}")
    #Akan dicetak keluaran seperti ini pada pemanggilan fungsi selanjutnya.

In [15]:
#Pertama kita meminta pengguna untuk menambahkan nama depan mereka.
first_name = input("Nama depan anda adalah : ")
#Setelahnya kita juga meminta pengguna menambahkan nama belakangnya.
last_name = input("Nama belakang anda adalah : ")
#Disini kita panggil fungsi yang ingin kita keluarkan.
full_nama(first_name,last_name)
#Maka keluaran yang akan didapatkan sebagai berikut :

Nama depan anda adalah : Jaya
Nama belakang anda adalah : Kusuma
Nama lengkapnya adalah Jaya Kusuma


In [16]:
#Contoh Fungsi Lainnya
#Disini saya akan membuat fungsi tentang luas layang-layang.

#pertama kita harus mengetahui bagaimana luas layang-layang.
#Luas layang-layang adalah 1/2 dikali dengan diagonal 1 dikali diagonal 2.
#Maka dapat saya simpulkan fungsinya adalah : 1/2 * d1 * d2.
#Berikut saya buat perintahnya :

#Disini saya membutuhkan dua variabel yaitu d1 dan d2
def Luas_LayangLayang(d1,d2):
    #Berikut adalah operas fungsi dari luas layang-layang
    Luas = (1/2)*d1*d2
    #perintah 'return' digunakan untuk memanggil kembali variabel fungsinya
    return Luas
    
#variabel x memanggil fungsi Luas_LayangLayang
x = Luas_LayangLayang(10,15)
print("Diketahui sebuah Layang-layang dengan diagonal pertamanya adalah 10 dan diagonal duanya adalah 15")
print("Maka luas layang-layang tersebut adalah : ", x)

Diketahui sebuah Layang-layang dengan diagonal pertamanya adalah 10 dan diagonal duanya adalah 15
Maka luas layang-layang tersebut adalah :  75.0


# 5.20 Numpy

In [17]:
#Numpy merupakan salah satu library didalam python yang dapat difungsikan dalam penghitungan
#menggunakan vektor dan matriks dalam beragam dimensi.

#Hal pertama yang dilakukan untuk memanggil library numpy dalam python ini dengan cara :
import numpy as np
#disini sebenarnya kita dapat mengimport numpy dalam beragam nama,
#namun biasanya kebanyakan orang menggunakan 'np'.

## 5.20.1 Perintah Dasar pada Numpy

In [18]:
#Disini dibuat sebuah data array dengan matriks berordo 1x4
a = np.array([0,1,2,3,4])
#dilakukan dengan mengimpor library Numpy yang telah diinisialkan dengan 'np' 
#serta membuat array dengan fungsi "np.array" untuk disimpan dalam variabel a
print(a)
#dilakukan pencetakan variabel a yang memiliki 1 baris dan 4 kolom dan berisi angka-angka yang telah dideklarasikan

[0 1 2 3 4]


In [19]:
#dibuat lagi sebuah data array dengan matriks berordo 2x4
b = np.array([[5,6,7,8],[9,8,7,6]])
#fungsi ini akan disimpan dalam variabel b
print(b)
#mencetak variabel b dengan baris 2 dan 4 kolom

[[5 6 7 8]
 [9 8 7 6]]


In [20]:
#dibuat lagi sebuah data array dengan matriks berordo 6x4
c = np.array([[[0,1,2,3],[4,5,6,7],[8,9,8,7],[6,5,4,3],[1,2,3,4],[5,6,7,8]]])
#fungsi ini akan disimpan dalam variabel c
print(c)
#mencetak variabel c dengan baris 6 dan 4 kolom

[[[0 1 2 3]
  [4 5 6 7]
  [8 9 8 7]
  [6 5 4 3]
  [1 2 3 4]
  [5 6 7 8]]]


In [21]:
#variabel.ndim
#digunakan untuk mengetahui jumlah dimensi dari sebuah array dalam Numpy
#sehingga sistem akan mencetak dimensi matriks dari array tersebut
a.ndim

1

In [22]:
b.ndim

2

In [23]:
c.ndim

3

In [24]:
#variabel.shape
#digunakan untuk mengetahuo jumlah baris dan kolom dalam sebuah array di numpy
#baris akan dicetak terlebih dahulu, kemudian dilanjutkan dengan kolom
a.shape
#disini akan dicetak'(5,)' yang artinya memiliki 1 baris dan 5 kolom

(5,)

In [25]:
b.shape

(2, 4)

In [26]:
c.shape
#disini berarti 6 baris dan 4 kolom

(1, 6, 4)

## 5.20.2 Memanggil Anggota,Kolom dan Baris dengan Numpy

In [27]:
import numpy as jaya

In [28]:
#buatkan sebuah data array dengan matriks berordo 3x4
d = jaya.array ([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
#dilakukan dengan mengimpor library Numpy yang telah diinisialkan dengan 'jaya' 
#serta membuat array dengan fungsi "jaya.array" untuk disimpan dalam variabel d
print (d)
#mencetak array pada variabel d

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [29]:
d[0,3]
#Jadi disini akan dicetak data pada baris pertama dan kolom ketiga
#REMINDER : urutan pada python dimulai dari 0

4

In [30]:
#disini akan dicetak array dari baris ketiga dengan perintah berikut :
d[2,:]

array([ 9, 10, 11, 12])

In [31]:
#disini akan dicetak array dari kolom keempat dengan perintah berikut :
d[:,3]

array([ 4,  8, 12])

In [32]:
d[0, 1 : 3]
#Perintah ini akan memberikan keluaran berupa elemen pada baris pertama dan kolom kedua hingga kolom ketiga pada matriks
# 0 menunjukkan baris
# 1 : 3 menunjukkan indeks dari elemen matriks yang akan diambil

array([2, 3])

## 5.20.3 Matriks pada Numpy

In [33]:
import numpy as jacob

In [34]:
#Akan dibuat matriks dengan ukuran 2 baris dan 3 kolom dimana semua anggotanya adalah 1
jacob.ones ((2,3))
#fungsi (.ones) ini digunakan untuk memmbuat matriks berordo tertentu dengan semua elemennya memiliki nilai 1
# 2 menunjukkan baris
# 3 menunjukkan kolom

array([[1., 1., 1.],
       [1., 1., 1.]])

In [35]:
#Disini akan dibuat matriks dengan ukuran 3 baris dan 2 kolom yang anggotanya adalah 0
jacob.zeros((3,2))
#zeros berfungsi untuk menambahkan anggota 0

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [36]:
jacob.identity(4)
#Fungsi .identity digunakan untuk membuat sebuah matriks identitas 
#matriks identitas adalah matriks dimana elemen di diagonal utamanya adalah 1 sedangkan elemen lainnya bernilai 0

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [37]:
#Disini akan dibuat dua buah matriks yang memiliki 3 baris dan 4 kolom yang anggotanya 1
jacob.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [38]:
#fungsi full digunakan untuk membuat sebuah matriks dengan ukuran tertentu 
#yang semua elemen dalam matriks telah ditentukan melalui perintahnya
jacob.full((3,2),9)
#jadi disini akan dibuat matriks dengan 3 baris dan 2 kolom beranggotakan 9

array([[9, 9],
       [9, 9],
       [9, 9]])

In [39]:
#fungsi (.random.rand) digunakan untuk menghasilkan nilai acak dengan sebaran yang seragam antara 0 sampai 1
jacob.random.rand(4,3)
#perintah diatas akan menghasilkan matriks dengan
#4 baris dan 3 kolom, dimana elemennya adalah nilai acak
#yang terdistribusi seragam antara 0 sampai 1.

array([[0.49634178, 0.05668602, 0.04106966],
       [0.40378424, 0.68069099, 0.29862923],
       [0.44200417, 0.93460109, 0.9852986 ],
       [0.79852081, 0.6871365 , 0.94578615]])

In [40]:
#fungsi (.random.randint) digunakan untuk menghasilkan matriks
#dengan elemennya adalah nilai acak di antara 2 nilai yang telah ditentukan
jacob.random.randint(1,10,size=(3,4))
#telah ditentukan batas bawah adalah 1 dan batas atasnya adalah 10
#ukuran dari matriks adalah 3 baris dan 4 kolom
#elemen-elemen matirksnya adalah bilangan bulat antara 1-10 yang dijadikan matriks dan disusun acak.

array([[2, 6, 3, 3],
       [3, 1, 1, 7],
       [4, 5, 7, 5]])

## 5.20.4 Copy pada Numpy

In [41]:
import numpy as jin

In [42]:
a = jin.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [43]:
b = a
#karena sudah dideklarasikan b = a, maka anggota matriks b adalah anggota a.
print(b)

[1 2 3 4 5]


In [44]:
#disini kita akan mengubah elemen pertama pada b menjadi 10.
b[0] = 10
print(b)

[10  2  3  4  5]


In [45]:
#karena sudah dideklarasikan a=b maka anggota di a juga diubah sesuai dengan yang di b.
print(a)

[10  2  3  4  5]


In [46]:
c = jin.array([1,2,3,4,5])
print(c)

[1 2 3 4 5]


In [47]:
d = c.copy()
#kode diatas akan membuat salinan dari variabel c dan menempel salinan tersebut ke varianel d
#sehingga elemen dari c dan d akan sama
#tetapi, perubahan yang dilakukan pada variabel d tidak akan mempengaruhi variabel c.
print(d)

[1 2 3 4 5]


In [48]:
#Sebagai contoh disini kita akan mengganti elemen pertama dari d menjadi 10.
d[0]=10
print(d)

[10  2  3  4  5]


In [49]:
print(c)
#kita cek di variabel c, tenyata tidak ada perubahan sama sekali.

[1 2 3 4 5]


## 5.20.5 Operasi Matematika pada Numpy

In [50]:
import numpy as jackson

In [51]:
a+2
#karena sebelum ini a sudah diinput sebagai matriks dengan anggota [10, 2, 3, 4, 5],
#maka elemen dari a ditambahkan dengan dua.

array([12,  4,  5,  6,  7])

In [52]:
a-2
#ini juga sama, elemen dari a dikurangi 2.

array([8, 0, 1, 2, 3])

In [53]:
a*2
#elemen dari a dikali dengan 2.

array([20,  4,  6,  8, 10])

In [54]:
a/2
#elemen dari a dibagi dengan 2.

array([5. , 1. , 1.5, 2. , 2.5])

In [55]:
a**2
#elemen dari a dipangkatkan dengan 2.

array([100,   4,   9,  16,  25], dtype=int32)

In [56]:
b = jackson.array([6,7,8,9,10])
print(b)

[ 6  7  8  9 10]


In [57]:
a+b
#disini elemen dari matriks a akan dijumlahkan dengan elemen dari matriks b.

array([16,  9, 11, 13, 15])

In [58]:
a-b
#elemen dari matriks a akan dikurangi dengan elemen dari matriks b.

array([ 4, -5, -5, -5, -5])

In [59]:
a*b
#elemen dari matriks a akan dikalikan dengan elemen dari matriks b.

array([60, 14, 24, 36, 50])

In [60]:
a/b
#elemen dari matriks a akan dibagi dengan elemen dari matriks b.

array([1.66666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [61]:
b**a
#elemen dari matriks b akan dipangkatkan dengan elemen dari matriks a.

array([60466176,       49,      512,     6561,   100000], dtype=int32)

In [62]:
jackson.cos(a)
#disini akan menghitung nilai cos dari elemen matriks a.

array([-0.83907153, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [63]:
jackson.tan(a)
#disini akan menghitung nilai tan dari elemen matriks a.

array([ 0.64836083, -2.18503986, -0.14254654,  1.15782128, -3.38051501])

In [64]:
jackson.sin(a)
#disini akan menghitung nilai sin dari elemen matriks a.

array([-0.54402111,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [65]:
jackson.sinh(a)
#disini akan menghitung nilai sin hiperbolik dari elemen matriks a.

array([1.10132329e+04, 3.62686041e+00, 1.00178749e+01, 2.72899172e+01,
       7.42032106e+01])

In [66]:
jackson.sqrt(a)
#Operasi ini akan menghitung akar kuadrat dari anggota matriks a.

array([3.16227766, 1.41421356, 1.73205081, 2.        , 2.23606798])

## 5.20.6 Perkalian Matrik pada Numpy

In [67]:
import numpy as np

In [68]:
#deklarasikan variabel a dengan matriks 2x4.
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [69]:
#deklarasikan variabel b dengan matriks 2x4 juga.
b = np.array([[9,10,11,12],[13,14,15,16]])
print(b)

[[ 9 10 11 12]
 [13 14 15 16]]


In [70]:
#disini perintah c akan menghitung hasil kali dari matriks a dan b.
c = a*b
print(c)

[[  9  20  33  48]
 [ 65  84 105 128]]


In [71]:
d = np.array([[9,10],[11,12],[13,14],[15,16]])
print(d)

[[ 9 10]
 [11 12]
 [13 14]
 [15 16]]


In [72]:
e = np.matmul(a,d)
# fungsi 'matmul()' berfungsi untuk mengalikan kedua matriks yaitu matriks a dan d
print(e)

[[130 140]
 [322 348]]


## 5.20.7 Min,Max dan Sum pada Numpy

In [73]:
import numpy as np

In [74]:
a = np.array([[1,2,3,4],
             [5,6,7,8],[9,10,11,12]])
print (a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [75]:
b = np.min(a)
#fungsi min adalah untuk mencari nilai terkecil dari suatu matriks
#jadi disini nilai terkecil di dalam matriks a adalah 1.
print(b)

1


In [76]:
c = np.min(a,axis=0)
#axis = 0 menunjukkan kolom, jadi nilai terendah dalam seluruh kolom akan dicetak melalui perintah dibawah ini.
print(c)

[1 2 3 4]


In [77]:
d = np.min(a,axis=1)
#axis = 1 menunjukkan baris, jadi nilai terendah dalam seluruh baris akan dicetak melalui perintah dibawah ini.
print(d)

[1 5 9]


In [78]:
e = np.max(a)
#fungsi max adalah untuk mencari nilai terbesar dari suatu matriks
#jadi disini nilai terbesar di dalam matriks a adalah 12.
print(e)

12


In [79]:
f = np.max(a,axis=0)
#axis = 0 menunjukkan kolom, jadi nilai terbesar dalam seluruh kolom akan dicetak melalui perintah dibawah ini.
print(f)

[ 9 10 11 12]


In [80]:
g = np.max(a,axis=1)
#axis = 1 menunjukkan baris, jadi nilai terbesar dalam seluruh baris akan dicetak melalui perintah dibawah ini.
print(g)

[ 4  8 12]


In [81]:
h = np.sum(a)
#disini fungsi sum berfungsi untuk menjumlahkan seluruh anggota matriks.
print(h)

78


In [82]:
i = np.sum(a,axis=0)
#dari axis = 0, berarti akan dijumlahkan setiap kolomnya dan dicetak melalui perintah dibawah ini.
print(i)

[15 18 21 24]


In [83]:
j = np.sum(a,axis=1)
#dari axis = 1, berarti akan dijumlahkan setiap barisnya dan dicetak melalui perintah dibawah ini.
print(j)

[10 26 42]


# Terimakasih :)